coding-partner review
sj1978/coding-partner-review pull request #1
Opened 2021-11-08 19:26 UTC by sj1978

In this exercise I: 
Copy all the contents of index.html, style.css, index.js, and interactive.js for my coding partner to perform a code review to check for the correct use of Javascript Html and CSS.

2021-11-08 22:58 UTC, JasemDuncan commented
Hi @sj1978 ! 👌

Your Code is great, clean, and very clear.

There are many things to highlight:

- You used the appropriate declaration of objects using const.
- You used comparison(===) in the best way.

I think it would be better to implement some small things:

- Try to use de declaration on Top.
- Try to use more explicit variables.

2021-11-08 23:34 UTC, JasemDuncan requested changes
Please consider making the changes listed above.

2021-11-09 13:40 UTC, sj1978 commented on index.js
> +const listTodo = new Todos();
good suggestion!

2021-11-09 13:41 UTC, sj1978 reviewed
Added comment

2021-11-09 18:24 UTC, JasemDuncan commented
Thanks for implementing the changes @sj1978, now you can merge your code.
:muscle:

2021-11-09 21:16 UTC, JasemDuncan approved these changes
Thanks for updating your code. Is time to merge.

2021-11-09 21:19 UTC, merged